# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

# we've modified the:
#   - vendor/github.com/prometheus/client_golang/prometheus/registry.go
# and we don't expect `dep check` rolled this change back.
# noverify = ["github.com/prometheus/client_golang"]


# we doesn't need the vendor as the following isn't product codes
#   - pkg/qrcode/tools/main.go
ignored = ["github.com/PeterCxy/gozbar"] 

#
# user def
#

[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.6"

[[constraint]]
  name = "github.com/cloudfoundry/gosigar"
  version = "1.1.0"

[[constraint]]
  name = "github.com/docker/docker"
  version = "1.12.6"

[[constraint]]
  name = "github.com/docker/go-units"
  version = "0.3.3"

[[constraint]]
  branch = "master"
  name = "github.com/felixge/tcpkeepalive"

[[constraint]]
  branch = "master"
  name = "github.com/googollee/go-socket.io"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  name = "github.com/kr/pty"
  version = "1.1.2"

[[constraint]]
  name = "github.com/miekg/dns"
  version = "1.0.8"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "golang.org/x/text"
  version = "0.3.0"

[[constraint]]
  branch = "v1"
  name = "gopkg.in/check.v1"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/mgo.v2"

[[constraint]]
  name = "gopkg.in/natefinch/lumberjack.v2"
  version = "2.1"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true
